---
# Hillview service parameters
  # Network port where the servers listen for requests
  backend_port: 3569
  # Java heap size for Hillview service
  default_heap_size: "25g"
  # Folder where the hillview service is installed on remote machines
  service_folder: "~"
  # Version of Apache Tomcat to deploy
  tomcat_version: "9.0.4"
  # Tomcat installation folder name
  tomcat: "apache-tomcat-{{ tomcat_version }}"
  # If true delete old log files
  cleanup: False
